cerner/bunsen

CONTRIBUTORS.md, bunsen-core/src/main/java/com/cerner/bunsen/ValueSetUdfs.java, bunsen-core/src/main/java/com/cerner/bunsen/mappings/Ancestor.java, bunsen-core/src/main/java/com/cerner/bunsen/mappings/ConceptMaps.java, bunsen-core/src/main/java/com/cerner/bunsen/mappings/Hierarchies.java, bunsen-core/src/main/java/com/cerner/bunsen/mappings/Mapping.java, bunsen-core/src/main/java/com/cerner/bunsen/mappings/UrlAndVersion.java, bunsen-core/src/main/java/com/cerner/bunsen/mappings/Value.java, bunsen-core/src/main/java/com/cerner/bunsen/mappings/ValueSets.java, bunsen-core/src/main/java/com/cerner/bunsen/mappings/broadcast/BroadcastableConceptMap.java, bunsen-core/src/main/java/com/cerner/bunsen/mappings/broadcast/BroadcastableValueSets.java, bunsen-core/src/main/java/com/cerner/bunsen/mappings/systems/Loinc.java, bunsen-core/src/main/java/com/cerner/bunsen/mappings/systems/Snomed.java, bunsen-core/src/main/scala/com/cerner/bunsen/EncoderBuilder.scala, bunsen-core/src/main/scala/com/cerner/bunsen/SchemaConverter.scala, bunsen-core/src/test/java/com/cerner/bunsen/ValueSetUdfsTest.java, bunsen-core/src/test/java/com/cerner/bunsen/mappings/ConceptMapsTest.java, bunsen-core/src/test/java/com/cerner/bunsen/mappings/HierarchiesTests.java, bunsen-core/src/test/java/com/cerner/bunsen/mappings/ValueSetsTest.java, bunsen-core/src/test/java/com/cerner/bunsen/mappings/broadcast/BroadcastableValueSetsTest.java, bunsen-core/src/test/java/com/cerner/bunsen/mappings/systems/LoincTest.java, bunsen-core/src/test/java/com/cerner/bunsen/mappings/systems/SnomedTest.java, bunsen-core/src/test/resources/valuesets/married_maritalstatus.xml, docs/source/snomed_and_loinc.rst, python/bunsen/mapping/__init__.py, python/bunsen/mapping/loinc.py, python/bunsen/mapping/snomed.py, python/bunsen/valuesets.py, python/tests/resources/valuesets/married_maritalstatus.xml, python/tests/test_bunsen.py
This PR provides the enhancement described in #3, adding support for FHIR ValueSets and changing the underlying implementation of the `ValueSetUdfs` class to utilize ValueSets and a new Hierarchies class rather than ConceptMaps. 
Additionally, it enforces immutable semantics across all tables holding data for ValueSets, ConceptMaps, and Hierarchies by ensuring the Url and Versions for the resources are unique.
It also makes minor changes to normalize style/doc where inconsistencies/misspellings were encountered.
This PR adds a full test suite for ValueSets and Hierarchies, and additional test cases in the Python API over ValueSet functions and ValueSetUdf functions.
=> Issue 3: Support Broadcasting the FHIR ValueSet

docs/source/snomed_and_loinc.rst, python/bunsen/mapping/__init__.py, python/bunsen/valuesets.py, python/tests/test_bunsen.py
Simplify using separate databases for ontologies for issue #6.
=> Issue #6: simplify using separate databases for custom ontologies.

python/bunsen/codes/__init__.py, python/tests/resources/conceptmaps/gender.xml, python/tests/test_bunsen.py
Resolves issue #11. Exposes the `withDirectory` methods in `ValueSets` and `ConceptMaps` in the Python API.
I've added unit tests that check the exposed methods. I also noticed a bug with the way we were referencing column names in the Python codebase. See a description in the file diff.
=> issue-11: adding withDirectory to value_sets and concept_maps

bunsen-core/src/main/java/com/cerner/bunsen/ValueSetUdfs.java
Resolves #32, to expose a method signature for `pushUdf` that accepts an already-broadcast BroadcastableValueSets instance.
Existing unit-tests hit this new code-path.
=> issue-32: adding new signature

.gitignore, python/bunsen/codes/__init__.py, python/pom.xml, python/tests/test_bunsen_r4.py, python/tests/test_bunsen_stu3.py
Fixes #38.
Adds a `new_version` parameter to the [`add_values`](https://engineering.cerner.com/bunsen/0.4.3/stu3_pythonapis.html#bunsen.codes.ValueSets.add_values) method of `ValueSets`. Includes STU3 and R4 tests.
=> issue-38: adding new_version parameter and tests

bunsen-r4/src/main/java/com/cerner/bunsen/r4/codes/ConceptMaps.java, bunsen-r4/src/test/java/com/cerner/bunsen/r4/codes/broadcast/BroadcastableMappingsTest.java, bunsen-stu3/src/main/java/com/cerner/bunsen/stu3/codes/ConceptMaps.java, bunsen-stu3/src/test/java/com/cerner/bunsen/stu3/codes/broadcast/BroadcastableMappingsTest.java
Fixes #40, wherein ConceptMaps having URIs with multiple distinct versions would fail to broadcast due to a map-key collision.
=> issue-40: fixing uri-to-version usage and adding test case

CONTRIBUTORS.md, bunsen-r4/src/test/java/com/cerner/bunsen/r4/FhirEncodersTest.java, bunsen-r4/src/test/java/com/cerner/bunsen/r4/SchemaConverterTest.java, bunsen-r4/src/test/java/com/cerner/bunsen/r4/TestData.java, pom.xml
Upgrade of the HAPI dependencies to version 3.6.0.
=> Upgrade HAPI to 3.6.0

bunsen-shaded/pom.xml, pom.xml
Fixes #48.
Uplifts project to use Spark 2.3.2. It appears the R4 FHIR dependencies require the Apache `commons-text` library to be shaded, otherwise R4 python tests fail with the relevant class not being on the classpath.
Built and ran regressions locally, tested in Notebook environment.
=> issue-48: Uplifting to spark-2.3.2

bunsen-core/src/main/java/com/cerner/bunsen/Bundles.java, bunsen-core/src/main/java/com/cerner/bunsen/FhirEncoders.java, bunsen-core/src/main/scala/com/cerner/bunsen/EncoderBuilder.scala, bunsen-core/src/main/scala/com/cerner/bunsen/SchemaConverter.scala, bunsen-r4/src/test/java/com/cerner/bunsen/r4/BundlesTest.java, bunsen-r4/src/test/java/com/cerner/bunsen/r4/FhirEncodersTest.java, bunsen-r4/src/test/java/com/cerner/bunsen/r4/TestData.java, bunsen-r4/src/test/resources/json/bundles/patient-1032702.fhir-bundle.json, bunsen-r4/src/test/resources/json/bundles/patient-6666001.fhir-bundle.json, bunsen-r4/src/test/resources/xml/bundles/patient-1032702.fhir-bundle.xml, bunsen-r4/src/test/resources/xml/bundles/patient-6666001.fhir-bundle.xml, bunsen-stu3/src/main/scala/com/cerner/bunsen/stu3/Stu3DataTypeMappings.scala, bunsen-stu3/src/test/java/com/cerner/bunsen/stu3/BundlesTest.java, bunsen-stu3/src/test/java/com/cerner/bunsen/stu3/FhirEncodersTest.java, bunsen-stu3/src/test/java/com/cerner/bunsen/stu3/TestData.java, bunsen-stu3/src/test/resources/json/bundles/patient-1032702.fhir-bundle.json, bunsen-stu3/src/test/resources/json/bundles/patient-6666001.fhir-bundle.json, bunsen-stu3/src/test/resources/xml/bundles/patient-1032702.fhir-bundle.xml, bunsen-stu3/src/test/resources/xml/bundles/patient-6666001.fhir-bundle.xml, python/bunsen/r4/bundles.py, python/bunsen/stu3/bundles.py
Resolves #46. 
Adds support for Contained Resources by allowing the user to declare a static listing of Resources that will be Contained. `Encoder` functions are then generated to inline Contained Resources to the Parent resource.
FHIR views Contained Resources as a List having a `Resource` type. Spark Schema won't meaningfully understand that parent type, so we create a "contained" struct having a field for each declared Resource type to serialize to. Deserialization puts the elements of the Struct back into the FHIR Contained list.
Tested by adding new unit tests. Ran a Jupyter session testing the `extract_entry` method over both STU3 and R4 content for bundles having Contained resources.
=> Issue 46: Support for Contained Resources

bunsen-core/src/main/java/com/cerner/bunsen/FhirEncoders.java, bunsen-r4/src/test/java/com/cerner/bunsen/r4/FhirEncodersTest.java
Resolves #51.
Adds a new method that allows a singleton resource definition for the encoder, resolves any ambiguity in calls to `FhirEncoders.of` that would not have had any contained resources.
Tested with existing regression suite, passive change.
=> issue-51: adding api cleanup for FhirEncoders.of

bunsen-avro-records-stu3/src/test/java/com/cerner/bunsen/avro/SpecificRecordsTest.java, bunsen-avro/src/main/java/com/cerner/bunsen/avro/converters/DefinitionToAvroVisitor.java
Any FHIR resource object instantiation fails, when its constructed using the corresponding FHIR Avro schema's builder method.
The following exception occurs when the "default" value is not set for fields in generated/source avpr file
```
org.apache.avro.AvroRuntimeException: org.apache.avro.AvroRuntimeException: Field meta type:UNION pos:1 not set and has no default value
at com.cerner.bunsen.stu3.avro.Patient$Builder.build(Patient.java:2246)
```
Following links suggests the implemented solution
[1] https://stackoverflow.com/questions/22938124/avro-field-default-values
[2] https://avro.apache.org/docs/1.8.2/spec.html#Unions
=> Fix for FHIR resource object instantiation issue

python/requirements.txt
Closes #55 and bumps PySpark for Spark 2.4.4.
Follows up #54.
=> issue-55: bumping pyspark

bunsen-avro-records-stu3/pom.xml, bunsen-avro-records-stu3/src/test/java/com/cerner/bunsen/avro/SpecificRecordsTest.java, bunsen-avro/src/main/java/com/cerner/bunsen/avro/AvroConverter.java, bunsen-avro/src/main/java/com/cerner/bunsen/avro/converters/DefinitionToAvroVisitor.java, bunsen-avro/src/main/java/com/cerner/bunsen/avro/tools/GenerateSchemas.java, bunsen-avro/src/test/java/com/cerner/bunsen/avro/AvroConverterTest.java, bunsen-core-stu3/src/main/java/com/cerner/bunsen/definitions/stu3/Stu3StructureDefinitions.java, bunsen-core-stu3/src/test/java/com/cerner/bunsen/stu3/TestData.java, bunsen-core/src/main/java/com/cerner/bunsen/definitions/DefinitionVisitor.java, bunsen-core/src/main/java/com/cerner/bunsen/definitions/HapiChoiceConverter.java, bunsen-core/src/main/java/com/cerner/bunsen/definitions/HapiCompositeConverter.java, bunsen-core/src/main/java/com/cerner/bunsen/definitions/HapiContainedConverter.java, bunsen-core/src/main/java/com/cerner/bunsen/definitions/StructureDefinitions.java, bunsen-core/src/main/java/com/cerner/bunsen/definitions/StructureField.java, bunsen-spark/src/main/java/com/cerner/bunsen/spark/SparkRowConverter.java, bunsen-spark/src/main/java/com/cerner/bunsen/spark/converters/DefinitionToSparkVisitor.java, bunsen-spark/src/test/java/com/cerner/bunsen/spark/SparkRowConverterTest.java
Closes #62, adds support for Contained Resources.
**How**: Resources that are expected to be contained must be statically declared during creation of a `HapiConverter`. These Resources are then parsed along with their parent in such a way that the elements of a `DomainResource.contained` field can be transformed into a statically-typed list of Resource Container, a structure type having each Contained resource included as a field bearing the resource name. This Resource Container can then be converted back to a FHIR Resource's contained list.
**Note**: also fixes a bug with ChoiceTypes having references clashing with others of the same structure, but different possible referents.
=> issue-62: add Contained Resource Support

bunsen-avro/src/main/java/com/cerner/bunsen/avro/converters/DefinitionToAvroVisitor.java, bunsen-core-stu3/src/test/java/com/cerner/bunsen/stu3/TestData.java, bunsen-core/src/main/java/com/cerner/bunsen/definitions/DefinitionVisitorsUtil.java, bunsen-spark/src/main/java/com/cerner/bunsen/spark/SparkRowConverter.java, bunsen-spark/src/main/java/com/cerner/bunsen/spark/converters/DefinitionToSparkVisitor.java, bunsen-spark/src/test/java/com/cerner/bunsen/spark/SparkRowConverterTest.java
Fixes [issue-74](https://github.com/cerner/bunsen/issues/74).
For Composite, Reference, Extension and Choice types the [DefinitionToAvroVisitor](https://github.com/cerner/bunsen/blob/0.5.0-dev/bunsen-avro/src/main/java/com/cerner/bunsen/avro/converters/DefinitionToAvroVisitor.java), the visitor that generates `Avro` schema caches corresponding converters in a [map](https://github.com/cerner/bunsen/blob/78806aadc69811ce62b5298b608161def0708f24/bunsen-avro/src/main/java/com/cerner/bunsen/avro/converters/DefinitionToAvroVisitor.java#L46) and avoids going into a recursion if the same structure is already generated and available in map.
In this PR, refactored and applied similar caching to [DefinitionToSparkVisitor](https://github.com/cerner/bunsen/blob/0.5.0-dev/bunsen-spark/src/main/java/com/ …
=> [0.5.0-dev] issue-74: fix for missing nested fields in Spark row schema

bunsen-avro/src/main/java/com/cerner/bunsen/avro/converters/DefinitionToAvroVisitor.java, bunsen-avro/src/test/java/com/cerner/bunsen/avro/AvroConverterTest.java, bunsen-core/src/main/java/com/cerner/bunsen/definitions/EnumConverter.java, bunsen-core/src/main/java/com/cerner/bunsen/definitions/HapiConverter.java, bunsen-core/src/main/java/com/cerner/bunsen/definitions/PrimitiveConverter.java, bunsen-spark/src/main/java/com/cerner/bunsen/spark/converters/DefinitionToSparkVisitor.java, bunsen-spark/src/test/java/com/cerner/bunsen/spark/SparkRowConverterTest.java
Closes #80 
Adds an `EnumConverter` that can handle null status code conversion.
Also loosens the Converter APIs so that outside implementations can override some functions.
=> issue-80: adds support for null status

CONTRIBUTORS.md, bunsen-spark/src/main/java/com/cerner/bunsen/spark/codes/broadcast/BroadcastableValueSets.java, bunsen-spark/src/test/java/com/cerner/bunsen/spark/codes/broadcast/BroadcastableValueSetsTest.java, bunsen-spark/src/test/resources/log4j.properties
Issues were being seen when multiple threads were each building there own BroadcastableValueSets with unique Spark sessions.
BroadcastableValueSets had static Spark encoders which are not guaranteed to be thread safe. The encoders are now instantiated inline to prevent issues.
N/A
https://github.com/cerner/bunsen/issues/85
=> BroadcastableValueSets threading issue

.travis.yml
Temporary fix for [issue-93](https://github.com/cerner/bunsen/issues/93).
Forces build system distribution to "trusty" to pull **openjdk8** to workaround non-passive changes in Java 11 for Spark 2.4.4. 
@karthisuku @ysmwei
=> Fix for issue-93, forcing build system distribution to "trusty"

CONTRIBUTORS.md, bunsen-spark/src/main/java/com/cerner/bunsen/spark/SparkRowConverter.java
SparkRowConverter.forResource was not thread-safe causing intermittent NullPointerException in Spark cluster mode.  See #96 
This pull makes it thread-safe by adding synchronized keyword.  The issue has not occurred ever since consuming these changes, even when using the consistent AWS EMR recreation steps described on the issue.
I tried many times to write a unit test to recreate this issue, but could not, and it seems to be due to Spark local mode not introducing the same deserialization and multi-threading combination needed to recreate that Spark cluster mode introduces.  Using the same consistent AWS EMR recreation steps described on the issue is what I used for the following manual tests:
1. Without changes: fails in 46 seconds
1. Without changes: fails in 48 seconds
1. With …
=> issue-96: synchronize SparkRowConverter.forResource fixes intermittent NPE

pom.xml
Security fix, uplift HAPI FHIR version to 3.8.0
@ysmwei @sc036868 @karthisuku
=> Security fix, uplift HAPI FHIR version to 3.8.0

CONTRIBUTORS.md, bunsen-avro-records-stu3/pom.xml, bunsen-avro-records-stu3/src/test/java/com/cerner/bunsen/avro/SpecificRecordsTest.java, bunsen-avro/src/main/java/com/cerner/bunsen/avro/converters/DefinitionToAvroVisitor.java, bunsen-avro/src/main/java/com/cerner/bunsen/avro/tools/GenerateSchemas.java, bunsen-avro/src/test/java/com/cerner/bunsen/avro/tools/GenerateSchemasTest.java
In some generated avro schemas there is no default type for certain fields. The reason for this is because some field declarations in `DefinitionToAvroVisitor.java` defined null default types by using `(Object) null` rather than `JsonProperties.NULL_VALUE`, which is the preferred way to write a null object to JSON. This leads to the default field being excluded entirely from some schemas, which prevents users from using Builders for those generated objects without having to specify null for certain fields.
For completeness' sake:
If you have anything else that you think may be relevant to this issue, list it here. Additional information can help us better understand your changes and speed up the review process.
Please add your name to the [CONTRIBUTORS.md] file. Adding your name to the …
=> Change null declarations in DefinitionToAvroVisitor.java
